MovieTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('movie_tracker.urls')),
    url(r'^admin/', admin.site.urls),
]

movie_tracker/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Actor(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name.encode('utf-8')

class Keyword(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name.encode('utf-8')

class Movie(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.DateField(null=True)
    runtime = models.IntegerField()
    genres = models.CharField(max_length=2000)
    budget = models.IntegerField()
    overview = models.CharField(max_length=2000)
    tagline = models.CharField(max_length=2000)
    poster = models.CharField(max_length=2000, null=True)
    actors = models.ManyToManyField(Actor, blank=True)
    keywords = models.ManyToManyField(Keyword, blank=True)

    def __str__(self):
        return self.title.encode('utf-8')

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)
    date = models.DateTimeField(default=datetime.now, blank=True)


class ActorMovie(models.Model):
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    character = models.CharField(max_length=200)


class UserMovie(models.Model):
    WATCHED = 'watched'
    NOT_WATCHED = 'not_watched'
    STATUS_CHOICES = (
        (WATCHED, 'Watched'),
        (NOT_WATCHED, 'Not Watched'),
    )

    status = models.TextField(
        max_length=2,
        choices=STATUS_CHOICES,
        default=NOT_WATCHED,
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

movie_tracker/views/actors.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import pdb

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from movie_tracker.models import *
from django.core.paginator import Paginator


class Index(ListView):
    model = Actor
    template_name = 'actors/index.html'
    context_object_name = 'actors'
    paginate_by = 10


    def get_queryset(self):
        name = self.request.GET.get('actor','')

        return self.model.objects.filter(name__icontains=name)


class Show(DetailView):
    model = Actor
    template_name = 'actors/show.html'
    context_object_name = 'actor'

templates/actors/index.html
{% extends 'layout.html' %}
{% block  content %}
    {% for actor in actors %}

        <a href="{% url 'actors_show' pk=actor.pk %}">
            {{ actor.name }}

        </a>
        <hr/>
    {% endfor %}


    {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
        {% if page_obj.has_previous %}
            <a href="/actors?page={{ page_obj.previous_page_number }}"><button class="btn btn-primary">Previous</button></a>
        {% endif %}
            <span class="page-current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
            {% if page_obj.has_next %}
                <a href="/actors?page={{ page_obj.next_page_number }}"><button class="btn btn-primary">Next</button></a>
            {% endif %}
        </span>
     </div>
    {% endif %}
{% endblock %}

templates/actors/show.html
{% extends 'layout.html' %}

{% block content %}

    <h4>{{ actor.name }}</h4>
    <hr/>

    <h4>Movies where he played:</h4>
    <div class="row">
        {% for movie in actor.movie_set.all %}
            <div class="col-md-2 tvshow-card-container">
                <a href="{% url 'movies_show' pk=movie.pk %}">
                    <div class="thumbnail tvshow-card">
                        <div class="poster-container">
                            <img class="tvshow-poster" src="{{ movie.poster }}" alt="tvshow-image">
                        </div>
                        <div class="caption">
                            <h4 class="tvshow-title">{{ movie.title }} ({{ movie.release_date }})</h4>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>



{% endblock %}